counties_germany = {
 'Breisgau-Hochschwarzwald County',
 'Emmendingen County',
 'City of Freiburg i.Breisgau',
 'Konstanz County',
 'Lörrach County',
 'Ortenaukreis County',
 'Rottweil County',
 'Schwarzwald-Baar-Kreis County',
 'Tuttlingen County',
 'Waldshut County',
 'City of Baden-Baden',
 'Calw County',
 'Enzkreis County',
 'Freudenstadt County',
 'City of Heidelberg',
 'City of Karlsruhe',
 'Karlsruhe County',
 'City of Mannheim',
 'Neckar-Odenwald-Kreis County',
 'City of Pforzheim',
 'Rastatt County',
 'Rhein-Neckar-Kreis County',
 'Böblingen County',
 'Esslingen County',
 'Göppingen County',
 'Heidenheim County',
 'City of Heilbronn',
 'Heilbronn County',
 'Hohenlohekreis County',
 'Ludwigsburg County',
 'Main-Tauber-Kreis County',
 'Ostalbkreis County',
 'Rems-Murr-Kreis County',
 'Schwäbisch Hall County',
 'City of Stuttgart',
 'Alb-Donau-Kreis County',
 'Biberach County',
 'Bodenseekreis County',
 'Ravensburg County',
 'Reutlingen County',
 'Sigmaringen County',
 'Tübingen County',
 'City of Ulm',
 'Zollernalbkreis County',
 'City of Ansbach',
 'Ansbach County',
 'City of Erlangen',
 'Erlangen-Höchstadt County',
 'City of Fürth',
 'Fürth County',
 'Neustadt a.d.Aisch-Bad Windsheim County',
 'City of Nürnberg',
 'Nürnberger Land County',
 'Roth County',
 'City of Schwabach',
 'Weißenburg-Gunzenhausen County',
 'Deggendorf County',
 'Dingolfing-Landau County',
 'Freyung-Grafenau County',
 'Kelheim County',
 'City of Landshut',
 'Landshut County',
 'City of Passau',
 'Passau County',
 'Regen County',
 'Rottal-Inn County',
 'City of Straubing',
 'Straubing-Bogen County',
 'Altötting County',
 'Bad Tölz-Wolfratshausen County',
 'Berchtesgadener Land County',
 'Dachau County',
 'Ebersberg County',
 'Eichstätt County',
 'Erding County',
 'Freising County',
 'Fürstenfeldbruck County',
 'Garmisch-Partenkirchen County',
 'City of Ingolstadt',
 'Landsberg a.Lech County',
 'Miesbach County',
 'Mühldorf a.Inn County',
 'City of München',
 'München County',
 'Neuburg-Schrobenhausen County',
 'Pfaffenhofen a.d.Ilm County',
 'City of Rosenheim',
 'Rosenheim County',
 'Starnberg County',
 'Traunstein County',
 'Weilheim-Schongau County',
 'City of Bamberg',
 'Bamberg County',
 'City of Bayreuth',
 'Bayreuth County',
 'City of Coburg',
 'Coburg County',
 'Forchheim County',
 'City of Hof',
 'Hof County',
 'Kronach County',
 'Kulmbach County',
 'Lichtenfels County',
 'Wunsiedel i.Fichtelgebirge County',
 'City of Amberg',
 'Amberg-Sulzbach County',
 'Cham County',
 'Neumarkt i.d.OPf. County',
 'Neustadt a.d.Waldnaab County',
 'City of Regensburg',
 'Regensburg County',
 'Schwandorf County',
 'Tirschenreuth County',
 'City of Weiden i.d.OPf.',
 'Aichach-Friedberg County',
 'City of Augsburg',
 'Augsburg County',
 'Dillingen a.d.Donau County',
 'Donau-Ries County',
 'Günzburg County',
 'City of Kaufbeuren',
 'City of Kempten',
 'Lindau County',
 'City of Memmingen',
 'Neu-Ulm County',
 'Oberallgäu County',
 'Ostallgäu County',
 'Unterallgäu County',
 'City of Aschaffenburg',
 'Aschaffenburg County',
 'Bad Kissingen County',
 'Haßberge County',
 'Kitzingen County',
 'Main-Spessart County',
 'Miltenberg County',
 'Rhön-Grabfeld County',
 'City of Schweinfurt',
 'Schweinfurt County',
 'City of Würzburg',
 'Würzburg County',
 'City of Berlin Charlottenburg-Wilmersdorf',
 'City of Berlin Friedrichshain-Kreuzberg',
 'City of Berlin Lichtenberg',
 'City of Berlin Marzahn-Hellersdorf',
 'City of Berlin Mitte',
 'City of Berlin Neukölln',
 'City of Berlin Pankow',
 'City of Berlin Reinickendorf',
 'City of Berlin Spandau',
 'City of Berlin Steglitz-Zehlendorf',
 'City of Berlin Tempelhof-Schöneberg',
 'City of Berlin Treptow-Köpenick',
 'Barnim County',
 'City of Brandenburg a.d.Havel',
 'City of Cottbus',
 'Dahme-Spreewald County',
 'Elbe-Elster County',
 'City of Frankfurt (Oder)',
 'Havelland County',
 'Märkisch-Oderland County',
 'Oberhavel County',
 'Oberspreewald-Lausitz County',
 'Oder-Spree County',
 'Ostprignitz-Ruppin County',
 'City of Potsdam',
 'Potsdam-Mittelmark County',
 'Prignitz County',
 'Spree-Neiße County',
 'Teltow-Fläming County',
 'Uckermark County',
 'City of Bremen',
 'City of Bremerhaven',
 'City of Hamburg',
 'Bergstraße County',
 'City of Darmstadt',
 'Darmstadt-Dieburg County',
 'City of Frankfurt am Main',
 'Groß-Gerau County',
 'Hochtaunuskreis County',
 'Main-Kinzig-Kreis County',
 'Main-Taunus-Kreis County',
 'Odenwaldkreis County',
 'City of Offenbach',
 'Offenbach County',
 'Rheingau-Taunus-Kreis County',
 'Wetteraukreis County',
 'City of Wiesbaden',
 'Gießen County',
 'Lahn-Dill-Kreis County',
 'Limburg-Weilburg County',
 'Marburg-Biedenkopf County',
 'Vogelsbergkreis County',
 'Fulda County',
 'Hersfeld-Rotenburg County',
 'City of Kassel',
 'Kassel County',
 'Schwalm-Eder-Kreis County',
 'Waldeck-Frankenberg County',
 'Werra-Meißner-Kreis County',
 'Ludwigslust-Parchim County',
 'Mecklenburgische Seenplatte County',
 'Nordwestmecklenburg County',
 'City of Rostock',
 'Rostock County',
 'City of Schwerin',
 'Vorpommern-Greifswald County',
 'Vorpommern-Rügen County',
 'City of Braunschweig',
 'Gifhorn County',
 'Goslar County',
 'Göttingen County',
 'Helmstedt County',
 'Northeim County',
 'Peine County',
 'City of Salzgitter',
 'Wolfenbüttel County',
 'City of Wolfsburg',
 'Diepholz County',
 'Hameln-Pyrmont County',
 'Greater Hannover',
 'Hildesheim County',
 'Holzminden County',
 'Nienburg (Weser) County',
 'Schaumburg County',
 'Celle County',
 'Cuxhaven County',
 'Harburg County',
 'Heidekreis County',
 'Lüchow-Dannenberg County',
 'Lüneburg County',
 'Osterholz County',
 'Rotenburg (Wümme) County',
 'Stade County',
 'Uelzen County',
 'Verden County',
 'Ammerland County',
 'Aurich County',
 'Cloppenburg County',
 'City of Delmenhorst',
 'City of Emden',
 'Emsland County',
 'Friesland County',
 'Grafschaft Bentheim County',
 'Leer County',
 'City of Oldenburg',
 'Oldenburg County',
 'City of Osnabrück',
 'Osnabrück County',
 'Vechta County',
 'Wesermarsch County',
 'City of Wilhelmshaven',
 'Wittmund County',
 'City of Bochum',
 'City of Dortmund',
 'Ennepe-Ruhr-Kreis County',
 'City of Hagen',
 'City of Hamm',
 'City of Herne',
 'Hochsauerlandkreis County',
 'Märkischer Kreis County',
 'Olpe County',
 'Siegen-Wittgenstein County',
 'Soest County',
 'Unna County',
 'City of Bielefeld',
 'Gütersloh County',
 'Herford County',
 'Höxter County',
 'Lippe County',
 'Minden-Lübbecke County',
 'Paderborn County',
 'City of Duisburg',
 'City of Düsseldorf',
 'City of Essen',
 'Kleve County',
 'City of Krefeld',
 'Mettmann County',
 'City of Mönchengladbach',
 'City of Mülheim a.d.Ruhr',
 'City of Oberhausen',
 'City of Remscheid',
 'Rhein-Kreis Neuss County',
 'City of Solingen',
 'Viersen County',
 'Wesel County',
 'City of Wuppertal',
 'Greater Aachen',
 'City of Bonn',
 'Düren County',
 'Euskirchen County',
 'Heinsberg County',
 'City of Köln',
 'City of Leverkusen',
 'Oberbergischer Kreis County',
 'Rhein-Erft-Kreis County',
 'Rheinisch-Bergischer Kreis County',
 'Rhein-Sieg-Kreis County',
 'Borken County',
 'City of Bottrop',
 'Coesfeld County',
 'City of Gelsenkirchen',
 'City of Münster',
 'Recklinghausen County',
 'Steinfurt County',
 'Warendorf County',
 'Ahrweiler County',
 'Altenkirchen County',
 'Bad Kreuznach County',
 'Birkenfeld County',
 'Cochem-Zell County',
 'City of Koblenz',
 'Mayen-Koblenz County',
 'Neuwied County',
 'Rhein-Hunsrück-Kreis County',
 'Rhein-Lahn-Kreis County',
 'Westerwaldkreis County',
 'Alzey-Worms County',
 'Bad Dürkheim County',
 'Donnersbergkreis County',
 'City of Frankenthal',
 'Germersheim County',
 'City of Kaiserslautern',
 'Kaiserslautern County',
 'Kusel County',
 'City of Landau i.d.Pfalz',
 'City of Ludwigshafen',
 'City of Mainz',
 'Mainz-Bingen County',
 'City of Neustadt a.d.Weinstraße',
 'City of Pirmasens',
 'Rhein-Pfalz-Kreis County',
 'City of Speyer',
 'Südliche Weinstraße County',
 'Südwestpfalz County',
 'City of Worms',
 'City of Zweibrücken',
 'Bernkastel-Wittlich County',
 'Bitburg-Prüm County',
 'City of Trier',
 'Trier-Saarburg County',
 'Vulkaneifel County',
 'Merzig-Wadern County',
 'Neunkirchen County',
 'Saarlouis County',
 'Saarpfalz-Kreis County',
 'Sankt Wendel County',
 'Stadtverband Saarbrücken County',
 'City of Chemnitz',
 'Erzgebirgskreis County',
 'Mittelsachsen County',
 'Vogtlandkreis County',
 'Zwickau County',
 'Bautzen County',
 'City of Dresden',
 'Görlitz County',
 'Meißen County',
 'Sächsische Schweiz-Osterzgebirge County',
 'City of Leipzig',
 'Leipzig County',
 'Nordsachsen County',
 'Altmarkkreis Salzwedel County',
 'Anhalt-Bitterfeld County',
 'Börde County',
 'Burgenlandkreis County',
 'City of Dessau-Roßlau',
 'City of Halle',
 'Harz County',
 'Jerichower Land County',
 'City of Magdeburg',
 'Mansfeld-Südharz County',
 'Saalekreis County',
 'Salzlandkreis County',
 'Stendal County',
 'Wittenberg County',
 'Dithmarschen County',
 'City of Flensburg',
 'Herzogtum Lauenburg County',
 'City of Kiel',
 'City of Lübeck',
 'City of Neumünster',
 'Nordfriesland County',
 'Ostholstein County',
 'Pinneberg County',
 'Plön County',
 'Rendsburg-Eckernförde County',
 'Schleswig-Flensburg County',
 'Segeberg County',
 'Steinburg County',
 'Stormarn County',
 'Altenburger Land County',
 'Eichsfeld County',
 'City of Erfurt',
 'City of Gera',
 'Gotha County',
 'Greiz County',
 'Hildburghausen County',
 'Ilm-Kreis County',
 'City of Jena',
 'Kyffhäuserkreis County',
 'Nordhausen County',
 'Saale-Holzland-Kreis County',
 'Saale-Orla-Kreis County',
 'Saalfeld-Rudolstadt County',
 'Schmalkalden-Meiningen County',
 'Sömmerda County',
 'Sonneberg County',
 'City of Suhl',
 'Unstrut-Hainich-Kreis County',
 'Wartburgkreis County',
 'City of Weimar',
 'Weimarer Land County',
 'Unknown'}